### PR TITLE
Update build.gradle to newer ForgeGradle version

### PR DESCRIPTION
**Pull request by Justsnoopy30**
This is a pull request because I am not sure if it would mess it up or there was a reason it wasn't updated.

### CODE REVIEW

**Comment by Justsnoopy30** [comment]
@ahmed605 Why is travis-ci failing to build this?

**Comment by Justsnoopy30** [comment]
In the build log: 
`8.15s$ ./gradlew setup
> Task :mcp:downloadConfig FAILED
FAILURE: Build failed with an exception.
`

**Comment by Justsnoopy30** [comment]
Oh I think I know the problem.

**Comment by Justsnoopy30** [comment]
@ahmed605 Can you help fix this?

**Comment by ahmed605** [comment]
Modern MCP is not compatible with newer ForgeGradle versions.

**Comment by Justsnoopy30** [comment]
Why?

**Comment by ahmed605** [comment]
I don't know maybe the name of classes changed

**Comment by Justsnoopy30** [comment]
How can that be fixed?

**Comment by ahmed605** [comment]
BRB Soon!

**Comment by Justsnoopy30** [comment]
> Modern MCP is not compatible with newer ForgeGradle versions.

> I don't know maybe the name of classes changed
How can that be fixed?

> BRB Soon!
Okay.

**Comment by Justsnoopy30** [comment]
@ahmed605 Are you back?

**Comment by ahmed605** [comment]
@Justsnoopy30 sorry but I'm busy creating a Brand New Minecraft Forge Mod

**Comment by ahmed605** [comment]
@Justsnoopy30 if you interesting I made something like Shazam(Music ID app) but for minecraft as forge mod(MrCrayFish Device mod addon)
shazamine

**Comment by ahmed605** [comment]
Oh about Newer ForgeGradle versions support I will take a look on New ForgeGradle , New MCPconfing , Forge and Forge MDK to figure out how to support this

**Comment by ahmed605** [comment]
I'm trying a test now!

**Comment by ahmed605** [comment]
The Test Seems to be working!
I will update the branch 1.14.3 with the test files

**Comment by ahmed605** [comment]
@Justsnoopy30 the new test in 1.14.3 branch might fix Java 12 issue please test it and tell me the results

**Comment by Justsnoopy30** [comment]
Ok, great, I'm about to go to sleep.
Tomorrow I'll try it.

**Pull request closed without merging**
